# Site Settings
locale                   : "es_ES"
title                    : "Chuleta SEO"
title_separator          : "|"
name                     : "Emirodgar"
url                      : "https://chuletaseo.com"
twitter_username: emirodgar
github_username:  emirodgar
